### PR TITLE
Update 234_tree_template.h

### PR DESCRIPTION
**Pull request by Symmetry-Maniac**
Insert function now appears to be working. Yay! No updated display function though, I think Adam is still working on that. Also, I made sure I'm on the correct account this time.

### CODE REVIEW

**Comment by MrMepper** [comment]
Good job! Merging

**Comment by MrMepper** [comment]
There are some conflicts due to your fork not being updated to master file. Refork the repository  after saving your changes, then request another pull.

**Comment by Symmetry-Maniac** [comment]
How do I refork?

**Comment by MrMepper** [comment]
Delete repository from your profile. Go into settings to do it. Then click fork back on mine. MAKE SURE that your changes are saved somewhere else. Once you have my updated fork, go ahead and reapply the changes.

**Pull request closed without merging**
